[Output]
Format=disk
Bootable=yes
Bootloader=systemd-boot
RepartDirectories=mkosi.repart/root-only
ImageId=rutoll-dispatcher-noble-x86_64
Seed=00000000-0000-0000-0000-000000000005

[Content]
Packages=
  ubuntu-standard
  linux-generic
  systemd-boot
  systemd-boot-efi
  tree

  # GUI (минимальный desktop)
  ubuntu-desktop-minimal

  # NVIDIA driver
  nvidia-driver-550

[Build]
PostInstallationScripts=mkosi.postinst.chroot
