[Output]
Format=tar
Bootable=no
ImageId=rutoll-docker-noble-x86_64
Seed=00000000-0000-0000-0000-000000000010

[Content]
Packages=
  ubuntu-minimal
  bash
  coreutils
  apt
  ca-certificates
  curl
  jq
  vim
  openssh-client

[Build]
PostInstallationScripts=mkosi.postinst.chroot
