[base]
localhost ansible_connection=local

[controller]
localhost ansible_connection=local

[app]
localhost ansible_connection=local

[turnpike]
localhost ansible_connection=local

[dispatcher]
localhost ansible_connection=local
