# Базовый hardening SSH.
PermitRootLogin no

PasswordAuthentication yes
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no

UsePAM yes

X11Forwarding no
PrintMotd no
TCPKeepAlive yes
UseDNS no
AllowTcpForwarding yes
AllowAgentForwarding yes

ClientAliveInterval 300
ClientAliveCountMax 2

AllowUsers support tech

LogLevel VERBOSE
