# Базовый hardening SSH.
PermitRootLogin no

# По умолчанию запрещаем пароли (рекомендуется). Если нужно — переопределите локально.
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no

UsePAM yes

X11Forwarding no
PrintMotd no
TCPKeepAlive yes
UseDNS no
AllowTcpForwarding no
AllowAgentForwarding no

ClientAliveInterval 300
ClientAliveCountMax 2

# Разрешаем логин только для встроенных пользователей
AllowUsers support tech

LogLevel VERBOSE
