[Output]
Format=disk
Bootable=yes
Bootloader=systemd-boot
RepartDirectories=mkosi.repart/root-only
ImageId=rutoll-controller-noble-x86_64
Seed=00000000-0000-0000-0000-000000000002

[Content]
Packages=
  ubuntu-standard
  linux-generic
  systemd-boot
  systemd-boot-efi
  tree


[Build]
PostInstallationScripts=mkosi.postinst.chroot
